# Shell variables
# Generated by 'wal'
wallpaper='/home/harsh/Pictures/Pictures/gruvbox_forest-4.png'

# Special
background='#111313'
foreground='#e6decb'
cursor='#e6decb'

# Colors
color0='#111313'
color1='#95662D'
color2='#897565'
color3='#7E8376'
color4='#A9822C'
color5='#978877'
color6='#B3A38C'
color7='#e6decb'
color8='#a19b8e'
color9='#95662D'
color10='#897565'
color11='#7E8376'
color12='#A9822C'
color13='#978877'
color14='#B3A38C'
color15='#e6decb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
