--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/harsh/Pictures/Pictures/gruvbox_forest-4.png"

-- Special
background="#111313"
foreground="#e6decb"
cursor="#e6decb"

-- Colors
color0="#111313"
color1="#95662D"
color2="#897565"
color3="#7E8376"
color4="#A9822C"
color5="#978877"
color6="#B3A38C"
color7="#e6decb"
color8="#a19b8e"
color9="#95662D"
color10="#897565"
color11="#7E8376"
color12="#A9822C"
color13="#978877"
color14="#B3A38C"
color15="#e6decb"
